# Generated by Django 5.1.1 on 2024-09-11 07:28

import testdocker.common.models.Utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(default=testdocker.common.models.Utils.generate_student_id, max_length=50, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ORTHER', 'Orther')], max_length=10, null=True)),
            ],
        ),
    ]
