# Generated by Django 5.1.1 on 2024-09-12 08:37

import datetime
import django.db.models.deletion
import testdocker.common.models.Utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 37, 13, 166464))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 37, 13, 166480))),
                ('college_id', models.CharField(default=testdocker.common.models.Utils.generate_college_id, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 37, 13, 166464)),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 37, 13, 166480)),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_students', to='core.college'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 37, 13, 166464))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 37, 13, 166480))),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_id', models.CharField(default=testdocker.common.models.Utils.generate_teacher_id, max_length=50, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_teachers', to='core.college')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
