# Generated by Django 5.1.1 on 2024-09-12 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_college_student_created_at_student_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 39, 50, 272115, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='college',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 39, 50, 272135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 39, 50, 272115, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 39, 50, 272135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 39, 50, 272115, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 39, 50, 272135, tzinfo=datetime.timezone.utc)),
        ),
    ]
