# Generated by Django 5.1.1 on 2024-09-12 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_college_created_at_alter_college_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 45, 40, 984295, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='college',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 45, 40, 984319, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 45, 40, 984295, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 45, 40, 984319, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 45, 40, 984295, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 8, 45, 40, 984319, tzinfo=datetime.timezone.utc)),
        ),
    ]
